name: DeployX CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Docker Hub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # =========================
    # BUILD BACKEND
    # =========================

    - name: Build Backend Image
      run: |
        docker build -t priyangshu0011/deployx-backend:latest ./backend

    - name: Push Backend Image
      run: |
        docker push priyangshu0011/deployx-backend:latest

    # =========================
    # BUILD FRONTEND
    # =========================

    - name: Build Frontend Image
      run: |
        docker build --no-cache -t priyangshu0011/deployx-frontend:latest ./frontend

    - name: Push Frontend Image
      run: |
        docker push priyangshu0011/deployx-frontend:latest

    # =========================
    # DEPLOY TO EC2
    # =========================

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master

      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}

        script: |

          export KUBECONFIG=/home/ubuntu/.kube/config

          docker pull priyangshu0011/deployx-backend:latest

          docker pull priyangshu0011/deployx-frontend:latest

          kubectl set image deployment/backend-deployment \
          backend=priyangshu0011/deployx-backend:latest

          kubectl set image deployment/frontend-deployment \
          frontend=priyangshu0011/deployx-frontend:latest

          kubectl rollout restart deployment backend-deployment

          kubectl rollout restart deployment frontend-deployment

          kubectl delete pod -l app=backend

          kubectl delete pod -l app=frontend

          kubectl get pods
