name: DeployX CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Docker Hub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Backend Image
      run: |
        docker build -t priyangshu0011/deployx-backend:${{ github.sha }} ./backend

    - name: Push Backend Image
      run: |
        docker push priyangshu0011/deployx-backend:${{ github.sha }}

    - name: Build Frontend Image
      run: |
        docker build -t priyangshu0011/deployx-frontend:${{ github.sha }} ./frontend

    - name: Push Frontend Image
      run: |
        docker push priyangshu0011/deployx-frontend:${{ github.sha }}

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master

      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}

        script: |

          kubectl set image deployment/backend-deployment \
          backend=priyangshu0011/deployx-backend:${{ github.sha }}

          kubectl set image deployment/frontend-deployment \
          frontend=priyangshu0011/deployx-frontend:${{ github.sha }}

          kubectl rollout restart deployment backend-deployment

          kubectl rollout restart deployment frontend-deployment

          kubectl get pods
